version: '3.8'

services:
  dumb-llm-router:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME:-dumb-llm-router}
    
    # Security: Run as non-root user (Unraid standard)
    user: "99:100"
    
    # Security: Read-only root filesystem with specific writable mounts
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    
    ports:
      - "${HOST_PORT:-8005}:${CONTAINER_PORT:-8000}"
    
    env_file: .env
    
    volumes:
      - ${APPDATA}/dumb-llm-router-test/config:/config:rw
      # Add a writable temp directory if needed
      - ${APPDATA}/dumb-llm-router-test/tmp:/app/tmp:rw
    
    networks:
      - default
    
    restart: unless-stopped
    
    # Security: Drop unnecessary capabilities
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    
    # Security: No new privileges
    security_opt:
      - no-new-privileges:true
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://dumb-llm-router:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: ${DOCKER_NETWORK:-ai_net}
    external: true
