# Smart LLM Router Configuration

# Model Routing Configuration
routing:
  # Keywords that trigger direct search routing
  search_keywords:
    - "research"
    - "look up"
    - "lookup" 
    - "look-up"
    - "search"
    - "verify"
    - "`"
  
# Logging Configuration  
logging:
  level: INFO                              # DEBUG, INFO, WARNING, ERROR
  enable_detailed_routing_logs: false     # Set to true for debugging