# Smart LLM Router Configuration

# Model Routing Configuration
routing:
  primary_model: "Flash-Perplexity"           # Gemini Flash with Perplexity Pro search
  fallback_model: "Flash-Basic"               # Gemini Flash without search
  fast_search_model: "Flash-Perplexity-Fast" # For quick searches
  research_model: "Flash-Perplexity-Research" # For deep research tasks
  
# Logging Configuration  
logging:
  level: INFO                              # DEBUG, INFO, WARNING, ERROR
  enable_detailed_routing_logs: false     # Set to true for debugging